# Generated by Django 3.0.8 on 2021-06-08 07:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='attachments/')),
                ('decription', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('subcategory', models.CharField(blank=True, default='', max_length=50)),
                ('read', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productrekmends.categories')),
            ],
        ),
    ]
