# Generated by Django 3.0.8 on 2021-06-08 08:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productrekmends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='decription',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
