# Generated by Django 3.0.8 on 2021-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrekmends', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
