# Generated by Django 3.0.8 on 2021-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrekmends', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='attachments/')),
                ('description', models.TextField()),
                ('catname', models.CharField(default='', max_length=50)),
                ('oldprice', models.IntegerField()),
                ('newprice', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
