# Generated by Django 3.0.8 on 2021-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrekmends', '0007_auto_20210614_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
