# Generated by Django 3.0.8 on 2021-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrekmends', '0011_auto_20210628_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('code', models.CharField(default='', max_length=50)),
                ('link', models.URLField(default='', max_length=500)),
            ],
        ),
    ]
